name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# Définit le profil de connexion (doit correspondre à votre setup dbt Cloud)
profile: 'default'

# Définition des chemins vers les différents types de fichiers
model-paths: ["models"]      # Dossier des scripts SQL
seed-paths: ["seeds"]        # Dossier des fichiers CSV de données fixes
test-paths: ["tests"]        # Dossier des tests personnalisés (data tests)
macro-paths: ["macros"]      # Dossier des fonctions Jinja réutilisables

# Nettoyage des dossiers temporaires
clean-targets:
  - "target"
  - "dbt_packages"

# --- HIÉRARCHIE DES MODÈLES ---
# Configuration des matérialisations
models:
  jaffle_shop: # Le nom de votre projet
    staging:
      +materialized: view # Le staging est léger, on utilise des vues
    marts:
      +materialized: table # Le marts est pour la BI, on utilise des tables pour la performance