name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# Définit le profil de connexion (doit correspondre à votre connexion dbt Cloud)
profile: 'default'

# Dossiers où dbt cherche les fichiers
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuration des matérialisations
models:
  jaffle_shop: # Le nom de votre projet
    staging:
      +materialized: view # Le staging est léger, on utilise des vues
    marts:
      +materialized: table # Le marts est pour la BI, on utilise des tables pour la performance